### Actualizar Perfil Cliente
PUT http://localhost:8081/api/perfil-cliente/usuario@example.com
Content-Type: application/json

{
  "ocupacion": "Arquitecto de Software Senior",
  "activo": true,
  "verificado": true,
  "ratingPromedio": 4.8
}

